<!doctype html><html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Admin</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">    @include('components.dark-theme')
</head><body class="bg-light"><nav class="navbar navbar-dark bg-dark"><div class="container"><a class="navbar-brand fw-bold" href="{{ route('countries.index') }}">SupplyChain Admin</a><form method="POST" action="{{ route('logout') }}">@csrf<button class="btn btn-outline-light btn-sm">Logout</button></form></div></nav><main class="container py-4">
@if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif @if($errors->any())<div class="alert alert-danger">{{ $errors->first() }}</div>@endif
<div class="row g-3 mb-4">@foreach($stats as $label=>$value)<div class="col-md-4"><div class="card border-0 shadow-sm"><div class="card-body"><small class="text-muted text-uppercase">{{ $label }}</small><div class="display-6 fw-bold">{{ number_format($value) }}</div></div></div></div>@endforeach</div>
<ul class="nav nav-pills mb-3">@foreach(['ports'=>'Pelabuhan','users'=>'User','articles'=>'Artikel'] as $key=>$label)<li class="nav-item"><a class="nav-link {{ $tab===$key?'active':'' }}" href="?tab={{ $key }}">{{ $label }}</a></li>@endforeach</ul>
@if($tab==='ports')<div class="card border-0 shadow-sm"><div class="card-body"><h2 class="h5">Tambah Pelabuhan</h2><form method="POST" action="{{ route('admin.ports.store') }}" class="row g-2">@csrf @foreach(['port_name'=>'Nama','country_name'=>'Negara','latitude'=>'Latitude','longitude'=>'Longitude','harbor_size'=>'Ukuran'] as $name=>$label)<div class="col-md"><input class="form-control" name="{{ $name }}" placeholder="{{ $label }}" {{ $name!=='harbor_size'?'required':'' }}></div>@endforeach<div class="col-auto"><button class="btn btn-primary">Tambah</button></div></form></div><div class="card-header bg-white"><form><input type="hidden" name="tab" value="ports"><input class="form-control" name="q" value="{{ request('q') }}" placeholder="Cari pelabuhan atau negara"></form></div><div class="table-responsive"><table class="table mb-0"><thead><tr><th>Pelabuhan</th><th>Negara</th><th>Koordinat</th><th>Aksi</th></tr></thead><tbody>@foreach($ports as $port)<tr><td>{{ $port->port_name }}</td><td>{{ $port->country_name }}</td><td>{{ $port->latitude }}, {{ $port->longitude }}</td><td><form method="POST" action="{{ route('admin.ports.destroy',$port) }}">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger">Hapus</button></form></td></tr>@endforeach</tbody></table></div><div class="card-footer">{{ $ports->links() }}</div></div>
@elseif($tab==='users')<div class="card border-0 shadow-sm"><div class="card-body"><h2 class="h5">Tambah User</h2><form method="POST" action="{{ route('admin.users.store') }}" class="row g-2">@csrf<div class="col"><input class="form-control" name="name" placeholder="Nama" required></div><div class="col"><input class="form-control" type="email" name="email" placeholder="Email" required></div><div class="col"><input class="form-control" type="password" name="password" placeholder="Password" required></div><div class="col"><select class="form-select" name="role"><option>user</option><option>admin</option></select></div><div class="col-auto"><button class="btn btn-primary">Tambah</button></div></form></div><table class="table"><thead><tr><th>Nama</th><th>Email</th><th>Role</th><th>Aksi</th></tr></thead><tbody>@foreach($users as $user)<tr><td>{{ $user->name }}</td><td>{{ $user->email }}</td><td><span class="badge text-bg-secondary">{{ $user->role }}</span></td><td>@if(!$user->is(auth()->user()))<form method="POST" action="{{ route('admin.users.destroy',$user) }}">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger">Hapus</button></form>@endif</td></tr>@endforeach</tbody></table></div>
@else<div class="card border-0 shadow-sm"><div class="card-body"><h2 class="h5">Tambah Artikel</h2><form method="POST" action="{{ route('admin.articles.store') }}">@csrf<input class="form-control mb-2" name="title" placeholder="Judul" required><div class="row g-2 mb-2"><div class="col"><input class="form-control" name="category" placeholder="Kategori"></div><div class="col"><input class="form-control" name="source_url" placeholder="URL sumber"></div></div><textarea class="form-control mb-2" name="content" placeholder="Isi analisis" required></textarea><button class="btn btn-primary">Simpan</button></form></div><div class="list-group list-group-flush">@foreach($articles as $article)<div class="list-group-item d-flex justify-content-between"><div><b>{{ $article->title }}</b><br><small>{{ $article->category }}</small></div><form method="POST" action="{{ route('admin.articles.destroy',$article) }}">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger">Hapus</button></form></div>@endforeach</div></div>@endif
</main></body></html>
