<!doctype html>
<html lang="id">
<head>
    <meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
    <title>Global News Intelligence - SupplyChain RiskIntel</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css">
    <style>
        :root{--navy:#0b1425;--ink:#132238;--muted:#64748b;--line:#e5eaf1;--blue:#2563eb}body{background:#f1f5f9;color:var(--ink);font-family:Inter,system-ui,-apple-system,"Segoe UI",sans-serif}.topbar{background:var(--navy);color:#fff}.brand-mark{width:38px;height:38px;border-radius:11px;background:#fbbf24;color:#111827;display:grid;place-items:center}.hero{background:linear-gradient(120deg,#0b1425 0%,#172a4b 60%,#174a72 100%);color:#fff;border-radius:24px;overflow:hidden;position:relative}.hero:after{content:"";position:absolute;width:360px;height:360px;border-radius:50%;right:-110px;top:-180px;background:#38bdf833}.live-dot{width:9px;height:9px;background:#22c55e;border-radius:50%;box-shadow:0 0 0 5px #22c55e25;display:inline-block}.stat{background:#ffffff12;border:1px solid #ffffff22;border-radius:14px;padding:13px}.filter-btn{border-radius:50px}.filter-btn.active{background:var(--ink);color:#fff;border-color:var(--ink)}.news-card{border:0;border-radius:18px;overflow:hidden;box-shadow:0 5px 22px #0f172a0d;transition:.2s;height:100%}.news-card:hover{transform:translateY(-4px);box-shadow:0 14px 32px #0f172a1c}.news-image{width:100%;height:205px;object-fit:cover;background:#dbe5f1}.hero-image{height:310px}.news-title{font-size:1.04rem;line-height:1.35}.news-description{color:var(--muted);font-size:.88rem;display:-webkit-box;-webkit-line-clamp:3;-webkit-box-orient:vertical;overflow:hidden}.sentiment{font-size:.7rem;border-radius:40px;padding:6px 9px}.source-link{text-decoration:none;color:inherit}.source-link:hover{color:var(--blue)}.side-panel{background:#fff;border-radius:18px;box-shadow:0 5px 22px #0f172a0d}.country-flag{width:28px;height:20px;object-fit:cover;border-radius:4px}.empty-state{background:#fff;border:1px dashed #cbd5e1;border-radius:18px}.skeleton{animation:pulse 1.2s infinite;background:#e2e8f0}@keyframes pulse{50%{opacity:.5}}@media(max-width:767px){.hero{border-radius:0}.hero-image{height:220px}.news-image{height:190px}}
    </style>
    @include('components.dark-theme')
</head>
<body>
<nav class="topbar py-3"><div class="container-xl d-flex justify-content-between align-items-center"><a href="{{ route('countries.index') }}" class="d-flex align-items-center gap-2 text-white text-decoration-none"><span class="brand-mark"><i class="fa-solid fa-chart-simple"></i></span><div><b>SupplyChain RiskIntel</b><small class="d-block text-white-50">Global News Intelligence</small></div></a><div class="d-flex gap-2"><a href="{{ route('sentiments.index') }}" class="btn btn-outline-light btn-sm"><i class="fa-solid fa-brain me-1"></i>Sentimen</a><a href="{{ route('countries.index') }}" class="btn btn-light btn-sm"><i class="fa-solid fa-arrow-left"></i></a></div></div></nav>

<main class="container-xl py-4 py-lg-5">
    <section class="hero p-4 p-lg-5 mb-4"><div class="position-relative" style="z-index:2"><div class="d-flex align-items-center gap-2 small mb-3"><span class="live-dot"></span><span>LIVE INTELLIGENCE FEED</span><span class="text-white-50" id="lastUpdate">Diperbarui {{ now()->diffForHumans() }}</span></div><div class="row align-items-end"><div class="col-lg-7"><h1 class="display-6 fw-bold">Berita Rantai Pasok Global</h1><p class="text-white-50 mb-4">Pantau berita logistik, perdagangan, ekonomi, geopolitik, dan gangguan pengiriman dari seluruh negara dalam satu dashboard.</p><div class="input-group input-group-lg"><span class="input-group-text bg-white border-0"><i class="fa-solid fa-magnifying-glass"></i></span><input id="newsSearch" class="form-control border-0" placeholder="Cari berita, negara, atau topik..."></div></div><div class="col-lg-5 mt-4 mt-lg-0"><div class="row g-2"><div class="col-6"><div class="stat"><small class="text-white-50">Total berita</small><div class="h4 fw-bold mb-0" id="totalNews">{{ number_format($newsStats['total']) }}</div></div></div><div class="col-6"><div class="stat"><small class="text-white-50">Negara tercakup</small><div class="h4 fw-bold mb-0">{{ number_format($newsStats['countries']) }}</div></div></div><div class="col-6"><div class="stat"><small class="text-white-50">Sentimen positif</small><div class="h4 fw-bold text-success mb-0">{{ number_format($newsStats['positive']) }}</div></div></div><div class="col-6"><div class="stat"><small class="text-white-50">Peringatan negatif</small><div class="h4 fw-bold text-warning mb-0">{{ number_format($newsStats['negative']) }}</div></div></div></div></div></div></div></section>

    <div class="d-flex flex-wrap justify-content-between align-items-center gap-3 mb-4"><div class="d-flex flex-wrap gap-2" id="sentimentFilters"><button class="btn btn-sm btn-outline-secondary filter-btn active" data-filter="all">Semua</button><button class="btn btn-sm btn-outline-success filter-btn" data-filter="positive">Positif</button><button class="btn btn-sm btn-outline-secondary filter-btn" data-filter="neutral">Netral</button><button class="btn btn-sm btn-outline-danger filter-btn" data-filter="negative">Negatif</button></div><div class="small text-muted"><i class="fa-solid fa-rotate me-1"></i>Auto-refresh setiap 60 detik</div></div>

    <div class="row g-4"><div class="col-xl-9"><div class="row g-4" id="newsGrid" data-latest-id="{{ $newsItems->first()?->id ?? 0 }}">
        @forelse($newsItems as $item)
            @php $sentiment=strtolower($item->sentiment_status ?: 'neutral'); $fallback=['https://images.unsplash.com/photo-1578575437130-527eed3abbec?auto=format&fit=crop&w=900&q=80','https://images.unsplash.com/photo-1494412651409-8963ce7935a7?auto=format&fit=crop&w=900&q=80','https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=900&q=80']; $image=$item->image_url ?: $fallback[$item->id % count($fallback)]; @endphp
            <article class="col-md-6 news-item" data-search="{{ strtolower($item->title.' '.$item->description.' '.$item->country?->country_name) }}" data-sentiment="{{ $sentiment }}"><div class="card news-card"><img class="news-image" src="{{ $image }}" alt="{{ $item->title }}" loading="lazy" onerror="this.onerror=null;this.src='https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=900&q=80'"><div class="card-body p-4"><div class="d-flex justify-content-between align-items-center mb-3"><div class="d-flex align-items-center gap-2">@if($item->country)<img class="country-flag" src="https://flagcdn.com/w40/{{ strtolower($item->country->country_code) }}.png" alt=""><small class="fw-semibold">{{ $item->country->country_name }}</small>@else<small class="fw-semibold">Global</small>@endif</div><span class="badge sentiment text-bg-{{ $sentiment==='positive'?'success':($sentiment==='negative'?'danger':'secondary') }}">{{ $item->sentiment_status ?: 'Neutral' }}</span></div><h2 class="news-title fw-bold mb-2"><a class="source-link" href="{{ $item->source_url }}" target="_blank" rel="noopener">{{ $item->title }}</a></h2><p class="news-description mb-3">{{ $item->description ?: 'Buka sumber untuk membaca informasi selengkapnya.' }}</p><div class="d-flex justify-content-between align-items-center"><small class="text-muted"><i class="fa-regular fa-clock me-1"></i>{{ $item->created_at->diffForHumans() }}</small><a href="{{ $item->source_url }}" target="_blank" rel="noopener" class="btn btn-sm btn-outline-primary">Baca sumber <i class="fa-solid fa-arrow-up-right-from-square ms-1"></i></a></div></div></div></article>
        @empty
            <div class="col-12"><div class="empty-state text-center p-5"><i class="fa-regular fa-newspaper fa-3x text-muted mb-3"></i><h2 class="h5">Feed berita belum tersedia</h2><p class="text-muted">Konfigurasikan GNEWS_API_KEY lalu jalankan sinkronisasi intelijen.</p><code>php artisan countries:sync-intelligence --limit=25</code></div></div>
        @endforelse
    </div><div id="noResults" class="empty-state text-center p-5 d-none"><i class="fa-solid fa-magnifying-glass fa-2x text-muted mb-3"></i><h3 class="h6">Berita tidak ditemukan</h3></div></div>

    <aside class="col-xl-3"><div class="side-panel p-4 mb-4"><h2 class="h6 fw-bold mb-3"><i class="fa-solid fa-bolt text-warning me-2"></i>Topik Intelijen</h2>@foreach(['Logistics & Shipping','Trade & Economy','Geopolitical Risk','Weather Disruption','Port Congestion'] as $topic)<button class="topic-btn btn btn-light text-start w-100 mb-2 small" data-topic="{{ strtolower(explode(' ', $topic)[0]) }}">{{ $topic }}</button>@endforeach</div><div class="side-panel p-4"><h2 class="h6 fw-bold">Analisis Editor</h2><p class="small text-muted">Artikel internal dari tim SupplyChain RiskIntel.</p>@forelse($analysisItems as $article)<div class="border-top py-3"><span class="badge text-bg-light mb-1">{{ $article->category ?: 'Analisis' }}</span><div class="small fw-bold">{{ $article->title }}</div><small class="text-muted">{{ $article->created_at->format('d M Y') }}</small></div>@empty<p class="small text-muted mb-0">Belum ada artikel editor.</p>@endforelse</div></aside></div>
</main>

<script>
let activeFilter='all';const search=document.getElementById('newsSearch');
function applyFilters(){const q=search.value.toLowerCase().trim();let visible=0;document.querySelectorAll('.news-item').forEach(card=>{const matchText=!q||card.dataset.search.includes(q),matchSentiment=activeFilter==='all'||card.dataset.sentiment===activeFilter;card.classList.toggle('d-none',!(matchText&&matchSentiment));if(matchText&&matchSentiment)visible++});document.getElementById('noResults').classList.toggle('d-none',visible>0||document.querySelectorAll('.news-item').length===0)}
search.addEventListener('input',applyFilters);document.querySelectorAll('.filter-btn').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('.filter-btn').forEach(x=>x.classList.remove('active'));button.classList.add('active');activeFilter=button.dataset.filter;applyFilters()}));document.querySelectorAll('.topic-btn').forEach(button=>button.addEventListener('click',()=>{search.value=button.dataset.topic;applyFilters();scrollTo({top:500,behavior:'smooth'})}));
setInterval(async()=>{try{const response=await fetch('{{ url('/api/news') }}',{headers:{Accept:'application/json'}});if(response.ok){const payload=await response.json(),items=payload.data??[];document.getElementById('lastUpdate').textContent='Dicek '+new Date().toLocaleTimeString('id-ID');const latest=Number(document.getElementById('newsGrid').dataset.latestId||0);if(items[0]&&Number(items[0].id)>latest)location.reload()}}catch(error){console.debug('Pembaruan feed ditunda',error)}},60000);
</script>
</body></html>
